[project]
name = "langgraph-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-anthropic>=0.3.1",
    "langchain-aws>=0.2.10",
    "langgraph>=0.2.60",
    "langsmith>=0.2.6",
]
